# (candidate_id, pair, title, glow, screen_1, screen_2)
S = [
(62,"G","The soil he hid in his freezer","home freezer",
 "A spoonful of soil from Easter Island, collected in 1964. When his Montreal lab closed in 1983, the samples were ordered destroyed. Chemist Suren Sehgal quietly kept some vials in his home freezer.",
 "Inside was rapamycin, made by a soil bacterium. It blocks mTOR, a growth switch that tends to stay on as we age, letting cells return to their own clean-up process. Researchers still study it for exactly that."),
(85,"D","The warning label they took off","warning label",
 "For twenty-three years, a black box warning label sat on menopausal hormone therapy. It followed a 2002 study announcement that frightened a generation of women away from estrogen almost overnight.",
 "The average woman in that study was 63, more than a decade past menopause. In November 2025, the FDA announced it was removing the boxed warning. By then, many women had spent years without ever asking."),
(61,"H","The copper in young blood","young blood",
 "In 1973, at UC San Francisco, Loren Pickart isolated something from human plasma. A tiny peptide, just three amino acids, carrying a single atom of copper. Its levels are highest in young blood.",
 "GHK hands copper to skin cells called fibroblasts and nudges them toward repair: collagen, elastin and more. A natural human peptide could not be patented as a drug, so it waited two decades for cosmetics to find it."),
(63,"E","The acne cream that erased wrinkles","acne cream",
 "It went on sale in 1971 as an acne cream. Then dermatologist Albert Kligman noticed something about his older patients using it. Their skin looked smoother and less weathered than before.",
 "He published the effect in 1986. Tretinoin, a vitamin A derivative, shifts skin from breaking collagen down to building it. A wrinkle formulation was approved in 1995. In America, it stayed behind a prescription for decades."),
(65,"B","Two amino acids nobody could own","cheapest ingredients",
 "Your cells make their own master antioxidant, glutathione. With age, levels fall. The surprising reason: older cells run short of two of the cheapest ingredients in nutrition, glycine and cysteine.",
 "Swallowed glutathione mostly breaks down in the gut, so for decades the idea was written off. Researchers gave older adults glycine plus N-acetylcysteine instead. The raw materials sell by the kilo. Nobody can own them."),
(68,"I","The trial nobody would pay for","diabetes pill",
 "A cheap generic diabetes pill. Researcher Nir Barzilai wanted to test whether metformin could slow aging itself. In 2015, the FDA agreed to a trial design. Then came the real problem: money.",
 "Metformin activates AMPK, the cell's low-fuel sensor, echoing part of what fasting does. But a generic drug has no owner to profit from proof. The trial needed about $75 million, and funding arrived slowly, piece by piece."),
(69,"F","The cells that refuse to die","zombie cells",
 "Some cells stop dividing but refuse to die. Scientists call them zombie cells. They linger in tissue, leaking inflammatory signals into everything around them, and they build up as we age.",
 "In 2015, Mayo Clinic researchers tested a pairing: dasatinib and quercetin, a pigment found in onions and capers. It helped clear these cells in animals. A plant pigment cannot be patented, so the work leans on philanthropy."),
(74,"H","The mice that grew their hair back","ruby laser",
 "Budapest, 1967. Endre Mester aimed a weak ruby laser at shaved mice, expecting nothing good. Instead, the fur on their backs grew back faster than on the mice left in the dark.",
 "Red and near-infrared light is absorbed inside mitochondria, nudging energy output and prompting skin cells to lay down collagen. For decades it was dismissed as fringe laser therapy. Nobody owned light, so nobody funded it."),
(77,"D","The gland they let die","training school",
 "Behind your breastbone sits the thymus, the immune system's training school. From early adulthood it slowly turns to fat. Medicine treated that as normal aging, so almost nobody tried to reverse it.",
 "Greg Fahy proposed regrowing it in the 1980s. Unable to get a study funded, he first tested growth hormone on himself. Decades later, a small trial called TRIIM reported thymus tissue returning in nine men."),
(83,"G","The paper Nature threw away","Nature rejected",
 "In 1962, a colleague nudged the temperature on Ferruccio Ritossa's fruit fly incubator. The chromosomes puffed up in a pattern he had never seen. He wrote it up. Nature rejected the paper.",
 "It ran in a small journal and was barely cited for years. It described heat shock proteins, a repair crew that heat calls up to refold damaged proteins. It is one reason researchers now study the sauna."),
(166,"G","The sausage poison in the frown line","sausage poison",
 "In the 1820s, a German country doctor named Justinus Kerner was tracing a sausage poison that was killing his patients. He studied it closely, even tried it on himself, and wrote a strange prediction.",
 "In tiny amounts, he suggested, it might one day quiet an overactive muscle. The poison was botulinum toxin. It stops a nerve delivering its message to one specific muscle. Today it smooths frown lines."),
(169,"C","The crocus they sold for two thousand years","autumn crocus",
 "From the autumn crocus came a gout remedy written down before the Roman Empire. In America it was sold for over a century without formal approval, for about nine cents a pill.",
 "In 2009, one company ran a modest trial under an FDA program, won exclusivity, and the price jumped. Colchicine stops immune cells from crawling in to inflame a joint. Researchers now study it for the heart."),
(216,"H","The mice that opened their eyes too early","eyelids opened",
 "Newborn mice. Their eyelids opened days early. Their teeth arrived ahead of schedule. Around 1960, Stanley Cohen had injected them with an extract from mouse salivary glands, and something in it was speeding growth.",
 "He purified it: epidermal growth factor, a signal telling skin cells to divide and move. It helped earn him a Nobel Prize in 1986. After 40, skin makes less of it and hears it less clearly."),
(223,"B","The old brewers' young hands","decades younger",
 "A sake brewery in Japan, the 1970s. The elderly brewers had faces creased by years of work. But their hands, plunged into fermenting rice every day, looked decades younger than their faces.",
 "Scientists from Max Factor studied the yeast broth. The ferment is a soup of amino acids, organic acids and minerals that supports the skin barrier in lab studies. It became Pitera, sold for around $200 a bottle."),
(226,"C","The bark they used on the burns of Mexico City","powdered bark",
 "November 1984. A gas plant exploded outside Mexico City, burning thousands of people. Doctors and families turned to an old Mayan remedy from Chiapas: the powdered bark of a tree called tepezcohuite.",
 "The bark is rich in tannins and saponins, which form a protective film over damaged skin. In lab studies, extracts stimulated skin-building cells. Nobody could patent it, and trials stayed small. Forty years later, influencers found it."),
(40,"G","The mosquito man of Havana","mosquito man",
 "In 1881, Cuban physician Carlos Finlay told colleagues that yellow fever was spread by a mosquito. For twenty years he was ridiculed. People called him the mosquito man of Havana.",
 "In 1900, a US Army board under Walter Reed tested his idea and confirmed it. Mosquito control began in 1901. Havana, after centuries of epidemics, was free of yellow fever within months. Finlay had been right."),
(45,"G","The ordeal bean","ordeal poison",
 "In West Africa, the Calabar bean was an ordeal poison. In 1934, a junior doctor at a poor London hospital, Mary Walker, noticed one disease looked a lot like poisoning with curare.",
 "The disease was myasthenia gravis: muscles failing until eyelids drooped and swallowing stopped. She tried physostigmine, the bean's extract and curare's antidote. Within minutes, her patient's muscles worked again. They called it a miracle."),
(64,"E","The data that sat for seventeen years","every day",
 "Queensland, 1992. Researchers asked one group to wear sunscreen every day, not only at the beach. The trial was designed to answer a different question. A second answer sat inside the data.",
 "Did daily users age more slowly? Nobody analysed it for seventeen years. When results appeared in 2013, the daily group showed no detectable increase in skin aging over four and a half years. Plain SPF 15."),
(66,"I","Seven hundred and twenty million dollars, then silence","720 million",
 "In 2008, GlaxoSmithKline paid $720 million for Sirtris, a company built on resveratrol, the red wine compound, and drugs designed to switch on sirtuins, genes linked to repair and fasting.",
 "Headlines called it a fountain of youth. By 2010 the lead compound was shelved after disappointing results. In 2013 the site closed. Sirtuin science carries on elsewhere, but the grand promise went quiet."),
(70,"B","The strawberry that clears the zombies","strawberry aisle",
 "Researchers tested ten plant compounds for one rare ability: clearing senescent cells, the worn-out cells that linger with age. The most potent one had been sitting in the strawberry aisle the whole time.",
 "Its name is fisetin, a flavonol pigment. In mice, it pushed those lingering cells toward the end they had been avoiding. Human trials are small and grant-funded. Nobody can own a molecule that grows in fruit."),
(73,"C","The pomegranate most people cannot use","gut bacteria",
 "Pomegranates were supposed to help muscles. The studies kept coming out muddled. Then researchers found out why: the useful molecule is not in the fruit at all. Your gut bacteria have to make it.",
 "It is called urolithin A, and it helps cells clear out worn, leaky mitochondria. But only about a third to 40 percent of people carry the microbes that produce it. Most bodies simply could not convert the fruit."),
(76,"F","The two rats sewn together","young blood",
 "Scientists once joined old and young mice so they shared one circulation. The old animals repaired better. Everyone assumed young blood carried something magic. The truth turned out to run the other way.",
 "Irina and Michael Conboy found old blood carries inhibitors that slow repair. Dilute them, swapping some old plasma for saline and albumin, and old tissue in mice started repairing again. The magic was subtraction."),
(82,"I","The fabric dye in the face cream","textile dye",
 "First made in 1876 as a textile dye. Methylene blue went on to become one of the first fully synthetic drugs ever given to patients. Then it quietly stayed in hospital pharmacies.",
 "At low doses it shuttles electrons inside mitochondria. In lab studies on skin cells, researchers reported less aging behaviour and more collagen. Off patent since the nineteenth century, it had no company to champion it."),
(84,"E","The man who picked the subject nobody wanted","nobody wanted",
 "Yoshinori Ohsumi chose a subject nobody wanted: how cells break down their own parts. It was treated as boring garbage disposal. He said he picked it because nobody else was working on it.",
 "When nutrients run short, the cell wraps damaged parts in a membrane and digests them for fuel. It is called autophagy. Ohsumi mapped it in yeast in 1992. In 2016, it won him the Nobel Prize."),
(88,"A","The powder on the bodybuilding shelf","bodybuilding aid",
 "It sat on supplement shelves for years as a cheap bodybuilding aid. Alpha-ketoglutarate, a molecule your cells already use to make energy. Its levels fall with age. Nobody thought to test it.",
 "In 2020, the Buck Institute fed it to middle-aged mice. They showed lower inflammation and spent more of their lives healthy, especially the females. The answer had been sitting on the shelf the whole time."),
(94,"D","The sunscreen America was not allowed to buy","sunscreen filter",
 "Europe approved this sunscreen filter in 2000. Billions of people across Europe, Asia and Australia have used it since. It was submitted to the FDA in 2002. Americans still could not buy it.",
 "Bemotrizinol absorbs both UVA and UVB and stays stable in sunlight, with minimal absorption into skin. UVA is the light that quietly breaks down collagen. The American application sat for about two decades."),
(107,"A","The powder France banned","white powder",
 "Creatine was first isolated from meat in Paris in 1832. It is a white powder found naturally in beef and fish. In 2001, France's food safety agency raised an alarm, and its sale was banned.",
 "Creatine recharges ATP, the energy currency of muscle and brain cells. Vegetarians and older adults tend to start with the lowest stores. Today it is one of the most studied supplements in the world."),
(110,"B","The yellow root that matched the diabetes drug","yellow root",
 "Chinese medicine used a bitter yellow root for wasting thirst, the old name for diabetes, for around 1,500 years. Its active compound is berberine, also found in barberry.",
 "In 2004, a Beijing team showed in Nature Medicine that berberine lowers LDL cholesterol by a route different from statins. It also activates AMPK, the same energy switch metformin targets. Old medicine, new mechanism."),
(115,"G","The farmer who never grew up","ate clay",
 "Shiraz, Iran, 1958. A 21-year-old farmer looked about ten years old. He had never gone through puberty. He ate clay. The textbooks said human zinc deficiency was impossible.",
 "Young doctor Ananda Prasad suspected otherwise. Zinc is a cofactor for more than 300 enzymes, including ones that make testosterone and build immune cells. Prasad proved the deficiency was real. Oysters are among the richest sources."),
(124,"F","The gene they named after a chocolate","chocolate town",
 "In 1996, a lab in Hershey, Pennsylvania, found a new gene. They named it KISS1, after the chocolate town's famous Hershey's Kisses. For years it sat filed under an entirely different topic.",
 "Then researchers found its real role. Kisspeptin neurons in the brain fire the pulse that starts the whole sex hormone system. It is the ignition key that switches on puberty and fertility."),
(159,"H","The blood they lose in orbit","carbon monoxide",
 "Astronauts lose red blood cells in orbit. Since the 1960s, doctors blamed fluid shifts. A team in Ottawa found a way to check, by counting one thing in each astronaut's breath: carbon monoxide.",
 "Each time the body breaks down the haem in a red cell, one molecule of carbon monoxide is released. In space, the count went up and stayed up. Weightlessness makes the body destroy blood faster."),
(142,"A","The honey they called worthless but harmless","harmless substance",
 "When antibiotics arrived in the 1940s, honey as wound care was filed away as a worthless but harmless substance. In New Zealand, biochemist Peter Molan refused to let that stand.",
 "Mānuka honey carries methylglyoxal, which, with the honey's acidity and sugar, kills bacteria, even MRSA, in lab tests. Molan spent decades proving it. Medical-grade mānuka now dresses wounds in hospitals."),
(185,"G","The seed in the pharaoh's tomb","Tutankhamun's tomb",
 "Among the treasures in Tutankhamun's tomb were tiny black seeds. Dioscorides described them. Islamic tradition calls them a cure for everything but death. Western medicine filed it all under religion.",
 "The seed is Nigella sativa. Its oil's main active, thymoquinone, calms key inflammatory enzymes and has been studied for airway inflammation. A seed sold by the kilo in every market cannot be patented."),
(186,"I","The tears of the Chios trees","resin tears",
 "On one Greek island, Chios, a shrub weeps resin tears. Only villages in the south of the island produce it. People have chewed it for stomach trouble since the time of Hippocrates.",
 "In 1998, a letter in the New England Journal of Medicine showed mastic kills H. pylori, a stomach bacterium, in a dish. A mouse study said no, and the story was declared dead. Greek researchers kept testing."),
(187,"C","The Calabrian juice they poured away","poured away",
 "Bergamot grows almost nowhere but a narrow coast of Calabria, Italy. For two centuries the perfume trade wanted only its fragrant peel oil. The bitter juice was simply poured away as waste.",
 "That juice holds unusual compounds with a statin-like shape that act on the same cholesterol enzyme. The first trials came from a regional Calabrian university. Nobody can patent a citrus fruit, so evidence built slowly."),
(189,"B","The islanders who drank five cups a day","five cups",
 "On Panama's San Blas islands, the Kuna people drink around five cups of home-ground cocoa a day. They have almost no high blood pressure. When they move to the city, that changes.",
 "The key is epicatechin, which helps blood vessels make nitric oxide and relax. Most commercial chocolate is alkalised, stripping those flavanols out. The research was funded by a candy company, so many dismissed it."),
(205,"A","The tree tea that saved Cartier's frozen crew","tree tea",
 "Winter, 1535. Jacques Cartier's ships froze into the St Lawrence River. Scurvy was killing his crew. The local Iroquoian people showed them a tree tea, brewed from bark and needles.",
 "The men recovered. The tree was probably white cedar, rich in vitamin C. Centuries later, French researchers revisited the idea with maritime pine bark. Its compounds support collagen and help blood vessels relax."),
(208,"C","The pharaoh's red drink","red drink",
 "In Cairo, Dakar and Mexico City, street sellers pour a deep red drink brewed from hibiscus. It has been sipped since the pharaohs. Researchers decided to test it against a blood pressure drug.",
 "The drug was captopril. In a Mexican trial, hibiscus tea performed comparably. Its anthocyanins act on the same enzyme, ACE, and it works as a mild diuretic. A folk beverage, hiding in plain sight."),
(209,"E","The arctic root the Soviets studied in Russian","golden root",
 "On Siberian cliffs grows a golden root. Villagers gave it to newlyweds. From the 1960s, Soviet scientists tested it on soldiers and workers for stamina, and published almost everything in Russian.",
 "Rhodiola appears to soften the body's stress response, damping the cortisol spike and supporting mood chemistry. During the Cold War, the West treated Soviet research as unverifiable. A whole field stayed behind a language barrier."),
(212,"F","The five letters clipped from collagen","own collagen",
 "Five amino acids, clipped from your own collagen. In 1993, a Tennessee research group showed this tiny fragment acts like a message. When collagen breaks down, it tells skin cells to rebuild.",
 "The fragment is called KTTKS. Add a fatty tail and it reaches into skin more easily. It was published as wound-healing biology. Cheap and hard to own as a drug, it ended up in skincare instead."),
(213,"I","The Barcelona Botox in a bottle","Barcelona lab",
 "In the late 1990s, a Barcelona lab designed a peptide just six amino acids long. It copies a piece of the machinery nerves use to tell a muscle to contract. The nickname came fast.",
 "Botox in a bottle. It does not cut that machinery the way botulinum toxin does. It competes for a place in it, so the muscle under a wrinkle contracts a little less. It was labelled a cosmetic."),
(217,"D","The salmon DNA in the Italian clinic","salmon sperm",
 "DNA fragments purified from trout and salmon sperm. Since the 1950s, a small family pharmaceutical company in Sanremo, Italy, has sold it as a prescription for wound healing. Almost nobody outside Italy noticed.",
 "PDRN activates adenosine receptors on skin cells, switching on growth factors, new capillaries and collagen. The firm never filed it in the United States. Then Korea rebranded it as an injectable skin booster, and it went viral."),
(225,"E","The snail farmers whose cuts vanished","cuts healed",
 "Chile, the 1980s. A family raising garden snails for the French escargot trade noticed something about their workers. Their cuts healed fast, often without scars, and their hands stayed soft.",
 "The mucin a snail makes to repair its own shell carries allantoin, glycolic acid and growth-factor-like proteins. In lab studies it spurs skin cells to multiply and move. For years it was dismissed as slime."),
(228,"A","The glue the silk mills washed away","silk mills",
 "For centuries, women reeling silk kept their hands in hot cocoon water. They were known for smooth, uncracked hands. The silk mills boiled out the protein responsible and washed it into rivers.",
 "It is sericin, the glue that holds a cocoon together. It binds water like a sponge and forms a breathable film. On skin, studies show it reduces water loss and raises hydration. Industrial waste, for centuries."),
(229,"F","The fish-scale cure that became the peel","fruit acids",
 "Philadelphia, 1974. Two researchers found that simple fruit acids and milk acids cleared ichthyosis, a condition that makes skin thick and scaly like fish scales. Glycolic, lactic and citric acid.",
 "Alpha hydroxy acids loosen the bonds between dead skin cells so they shed. At higher strengths they signal deeper layers to make collagen. For a decade, the inventors were told peeling skin was a beautician's job."),
(230,"I","The orange that turned brown in the bottle","turned brown",
 "For decades, shelves sold vitamin C creams that had already turned brown. Vitamin C breaks down in air and water. In 1992, Duke dermatologist Sheldon Pinnell worked out how it actually enters skin.",
 "It only gets in as L-ascorbic acid, at a very acidic pH below 3.5. Skin needs vitamin C to build collagen. Ferulic acid and vitamin E helped stabilise it. Many of those early creams were simply dead."),
(235,"B","The fern you swallow before the sun","Central American",
 "A Central American fern called calaguala was used by Indigenous people in Honduras on inflamed skin. A Spanish company sold its extract for skin conditions. Then scientists noticed something about sunlight.",
 "Taken by mouth, its antioxidants appear to reach the skin. In studies, it reduced redness and cell damage from UV light. Sold as a supplement, it cannot be advertised as an oral sunscreen. It does not replace one."),
(237,"F","The old hands painted with the island drug","one hand",
 "Researchers at Drexel University asked what rapamycin, the Easter Island longevity drug, would do painted on skin instead of swallowed. Older volunteers applied it to one hand and a placebo to the other.",
 "Months later, the treated skin showed fewer markers of aging cells and more of a protein that anchors skin layers together. The patent expired long ago, so no company will pay for the large trial it needs."),
(238,"D","The weak estrogen they put on the face","first five",
 "In 1983, a London team showed in The Lancet that skin collagen drops by about 30 percent in the first five years after menopause. The cells that build it carry estrogen receptors.",
 "In 1996, a dermatology study applied estriol, the weakest natural estrogen, to the face at a tiny dose. Skin firmness and moisture improved. Then the 2002 estrogen scare arrived. One promising paper, then silence."),
(239,"H","The tattoo gun with no ink","no ink",
 "Montreal, 1997. A plastic surgeon tattooing scars with skin-coloured pigment noticed they improved beyond what the colour explained. The needle seemed to be doing the work. Others tried the tattoo gun with no ink.",
 "Thousands of tiny punctures trigger the wound-healing cascade and new collagen, while the surface heals within a day. A twenty-dollar roller had no patent, so it lived in the shadow of expensive lasers for years."),
]
